{
    banks {
        id
        name
    },
    bank(id: "3561217a-52e7-4816-a7f8-a2a8b52f6ce0") {
        id
        name
        articles {
            id
            title
        }
    },
    articles {
        id
        title
    },
}


mutation CreateBank {
    createBank(name: "Secon212d", crawler_url: "We're off to a great start!") {
        id
    }
}